#!/usr/bin/env node
/**
 * Creates src/environments/environment.ts, and android/app/google-services.json
 * once the Android platform exists, if they are missing.
 *
 * That file is git-ignored because it carries the Firebase project
 * configuration, and *nothing* in this repo compiles without it — not the
 * build, not the unit tests, not `tsc --noEmit`. A fresh clone therefore fails
 * on its first command with "Cannot find module '../../../environments/
 * environment'", which says nothing about the actual problem.
 *
 * Two callers need this:
 *
 *   - A developer who has just cloned the repo and wants to run the tests
 *     before setting up any Firebase access at all.
 *   - CI. A pull request from a fork has no access to repository secrets, so
 *     the lint, typecheck, test and build jobs cannot generate a real config.
 *     They do not need one: nothing contacts Firebase at build or unit-test
 *     time, since AuthService only signs in once the app is running in a
 *     browser.
 *
 * The values written here are deliberately obvious placeholders rather than
 * plausible-looking ones. An app that silently talks to the wrong Firebase
 * project is worse than an app that fails to connect, and "placeholder" in a
 * network error is a much faster diagnosis than a valid-looking key.
 *
 * An existing file is never overwritten — running this must be safe on a
 * machine that already has real credentials.
 */
import { existsSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const ROOT = resolve(import.meta.dirname, "..");

writeEnvironment();
writeGoogleServices();

function writeEnvironment() {
  const target = resolve(ROOT, "src/environments/environment.ts");

  if (existsSync(target)) {
    console.log("environment.ts already exists — left untouched.");
    return;
  }

  const contents = `import { Environment } from "./environment.template";

// Generated by \`npm run setup:env\`. Placeholder values: this configuration
// cannot reach any Firebase project. Replace it with the real one to use
// sign-in and cloud storage locally.
export const environment: Environment = {
  firebase: {
    apiKey: "placeholder-api-key",
    authDomain: "placeholder.firebaseapp.com",
    databaseURL: "https://placeholder-default-rtdb.firebaseio.com",
    projectId: "placeholder",
    storageBucket: "placeholder.appspot.com",
    messagingSenderId: "000000000000",
    appId: "1:000000000000:web:0000000000000000",
  },
};
`;

  writeFileSync(target, contents);
  console.log("Wrote src/environments/environment.ts with placeholder values.");
}

/**
 * The Android build has the same problem for a different file: the
 * google-services Gradle plugin refuses to configure the project without
 * android/app/google-services.json, which carries the Firebase Android app's
 * identifiers and so is git-ignored like environment.ts.
 *
 * The placeholder is enough for Gradle to run and for the APK to build; it is
 * not enough to sign in. Replace it with the file the Firebase console gives
 * you for an Android app registered under this applicationId, with your signing
 * certificate's SHA-1 added, or Google sign-in fails at runtime.
 *
 * Skipped entirely when android/ is absent — the platform is added on demand
 * with `npx cap add android`, and a fresh clone that only builds the PWA must
 * not have a stray file appear in a directory that does not exist.
 */
function writeGoogleServices() {
  const androidApp = resolve(ROOT, "android/app");
  if (!existsSync(androidApp)) return;

  const target = resolve(androidApp, "google-services.json");
  if (existsSync(target)) {
    console.log("google-services.json already exists — left untouched.");
    return;
  }

  const contents = {
    project_info: {
      project_number: "000000000000",
      project_id: "placeholder",
      storage_bucket: "placeholder.appspot.com",
    },
    client: [
      {
        client_info: {
          mobilesdk_app_id: "1:000000000000:android:0000000000000000",
          android_client_info: { package_name: "io.github.fauvet.guitab" },
        },
        oauth_client: [],
        api_key: [{ current_key: "placeholder-api-key" }],
        services: { appinvite_service: { other_platform_oauth_client: [] } },
      },
    ],
    configuration_version: "1",
  };

  writeFileSync(target, `${JSON.stringify(contents, null, 2)}\n`);
  console.log("Wrote android/app/google-services.json with placeholder values.");
}
