#!/usr/bin/env node
/**
 * Creates src/environments/environment.ts if it is missing.
 *
 * That file is git-ignored because it carries the Firebase project
 * configuration, and *nothing* in this repo compiles without it — not the
 * build, not the unit tests, not `tsc --noEmit`. A fresh clone therefore fails
 * on its first command with "Cannot find module '../../../environments/
 * environment'", which says nothing about the actual problem.
 *
 * Two callers need this:
 *
 *   - A developer who has just cloned the repo and wants to run the tests
 *     before setting up any Firebase access at all.
 *   - CI. A pull request from a fork has no access to repository secrets, so
 *     the lint, typecheck, test and build jobs cannot generate a real config.
 *     They do not need one: nothing contacts Firebase at build or unit-test
 *     time, since AuthService only signs in once the app is running in a
 *     browser.
 *
 * The values written here are deliberately obvious placeholders rather than
 * plausible-looking ones. An app that silently talks to the wrong Firebase
 * project is worse than an app that fails to connect, and "placeholder" in a
 * network error is a much faster diagnosis than a valid-looking key.
 *
 * An existing file is never overwritten — running this must be safe on a
 * machine that already has real credentials.
 */
import { existsSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const target = resolve(import.meta.dirname, "../src/environments/environment.ts");

if (existsSync(target)) {
  console.log("environment.ts already exists — left untouched.");
  process.exit(0);
}

const contents = `import { Environment } from "./environment.template";

// Generated by \`npm run setup:env\`. Placeholder values: this configuration
// cannot reach any Firebase project. Replace it with the real one to use
// sign-in and cloud storage locally.
export const environment: Environment = {
  firebase: {
    apiKey: "placeholder-api-key",
    authDomain: "placeholder.firebaseapp.com",
    databaseURL: "https://placeholder-default-rtdb.firebaseio.com",
    projectId: "placeholder",
    storageBucket: "placeholder.appspot.com",
    messagingSenderId: "000000000000",
    appId: "1:000000000000:web:0000000000000000",
  },
};
`;

writeFileSync(target, contents);
console.log("Wrote src/environments/environment.ts with placeholder values.");
